apiVersion: apps/v1
kind: Deployment
metadata:
  name: capstone-project
spec:
  replicas: 5
  selector:
    matchLabels:
      app: financeproject
  template:
    metadata:
      labels:
        app: financeproject
    spec:
      containers:
        - name: capstoneproject-container
          image: nkcharan/solar:v1
          ports:
            - containerPort: 8080
